name: Continuous Delivery teste
on:
  push:
    branches:
      - main
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: simulando continuous delivery
        uses: actions/upload-artifact@v4
        with:
          name: arquivoZip.zip
          path: |
            **.py
            README.md
      
testes:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov pytest-asyncio
        pytest Test/test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  
  

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: arquivoZip.zip
      - name: Display structure of downloaded files
        run: ls -R
