name: Continuous Delivery teste
on:
  push:
    branches:
      - main
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: simulando continuous delivery
        uses: actions/upload-artifact@v4
        with:
          name: arquivoZip.zip
          path: |
            **.py
            README.md
      

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: arquivoZip.zip
      - name: Display structure of downloaded files
        run: ls -R
